version: 4.7.{build}
skip_tags: true
image: Visual Studio 2017
build:
    project: log4net.RavenDB.sln
    publish_nuget: true             # package projects with .nuspec files and push to artifacts
    publish_nuget_symbols: true     # generate and publish NuGet symbol packages
    include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
    verbosity: detailed
test:
    assemblies:
            -'**\*Tests.dll'