version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
before_build:
    - nuget restore
build:
    project: log4net.RavenDB.sln
    publish_nuget: true             # package projects with .nuspec files and push to artifacts
    publish_nuget_symbols: true     # generate and publish NuGet symbol packages
    verbosity: minimal

test:
    assemblies:
            - **\*Tests.dll

on:
    branch: master
    appveyor_repo_tag: true